version: "3.9"
services: 
  web:
    build: .
    restart: always
    depends_on:
      - db
  db:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kwekker
    volumes:
      - db:/var/lib/postgresql/data
      - ./.docker/postgres/sql:/docker-entrypoint-initdb.d
    restart: always
volumes:
  db: